---
title: "Computing Assignment VII"
author: "redSloth: Tyler Hoppenfield, Daniel Mather, Iwunze Ugo"
date: "March 9, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r allcode, include=FALSE}
rm(list = ls())
cat("\014")

library(stargazer)
library(tidyverse)
library(readr)
library(AER)
library(knitr)
library(broom)
library(dplyr)

RSdata <- read_csv("~/Documents/Classes/Winter 2017/ECN 240A Econometrics/Section/PS7/RSdata.csv")

# OLS models

# supply model
supplyOLS <- lm(data = RSdata, ln_qs ~ ln_fp + trendsp1 + trendsp2 + trendsp3)

summary(supplyOLS)

# demand model
demandOLS <- lm(data = RSdata, ln_qd ~ ln_sp + trendsp1+ trendsp2+ trendsp3)

summary(demandOLS)

# The OLS coefficient for supply elasticity is XXX, which is somewhat close to the coefficient estimated in RS (XXX). Similary, the demand coefficients are similar as well (XXX vs. XXX). The authors, RS, use the OLS model to highlight the endogeneity of the price, which is shown through the likely underestimated supply elasticity and the likely overestimated demand elasticity. They estimate the OLS regressions without instrumenting prices, which is why the term ln_w is not included in the regression here.

# IV models

#supply model
supplyIV.firststage <- lm(data = RSdata, formula = ln_fp ~ lag_ln_w + ln_w + trendsp1 + trendsp2 + trendsp3)

supplyIV <- ivreg(data = RSdata, formula = ln_qs ~ ln_fp + ln_w + trendsp1 + trendsp2 + trendsp3 | trendsp1 + trendsp2 + trendsp3 + ln_w + lag_ln_w)

us <- c(coef(summary(supplyIV))["ln_fp","Estimate"], +
  coef(summary(supplyIV))["ln_fp","Std. Error"], +
  coef(summary(supplyIV))["ln_w","Estimate"], +
  coef(summary(supplyIV))["ln_w","Std. Error"], +
  coef(summary(supplyIV.firststage))["lag_ln_w","Estimate"], +
  coef(summary(supplyIV.firststage))["lag_ln_w","Std. Error"], +
  coef(summary(supplyIV.firststage))["ln_w","Estimate"], +
  coef(summary(supplyIV.firststage))["ln_w","Std. Error"])

rs <- c(0.096, 0.025, 1.229, 0.138, -3.628, 0.945, -2.276, 1.294)

compare.supplyIV <- data.frame(US = us, RS = rs)
row.names(compare.supplyIV) <- c("Supply elas.", "(std. error)", "Shock w(t)", "(std. error2)", "First stage w(t-1)", "(std. error3)", "First stage w(t)", "std. error4")

# demand model

demandIV.firststage <- lm(data = RSdata, formula = ln_sp ~ ln_w + trendsp1 + trendsp2 + trendsp3)

summary(demandIV.firststage)

demandIV <- ivreg(data = RSdata, formula = ln_qd ~ ln_sp + trendsp1 + trendsp2 + trendsp3 | trendsp1 + trendsp2 + trendsp3 + ln_w)

summary(demandIV)

# Our estimates of the supply and demand elasticities are similar to those in the RS paper.
```

## OLS Regression Results
``` {r results='asis', echo=FALSE}
stargazer(supplyOLS, header=FALSE, omit = c("trendsp1", "trendsp2", "trendsp3", "Constant"), covariate.labels = "supply elasticity")

stargazer(demandOLS, header=FALSE, omit = c("trendsp1", "trendsp2", "trendsp3", "Constant"), covariate.labels = "demand elasticity")
```

## IV Regression Results
```{r results='asis', echo=FALSE}
stargazer(supplyIV, supplyIV.firststage, header=FALSE, omit = c("trendsp1", "trendsp2", "trendsp3", "Constant"), covariate.labels = c("supply elasticity", "first stage w-1", "first stage w"))

stargazer(demandIV, demandIV.firststage, header=FALSE, omit = c("trendsp1", "trendsp2", "trendsp3", "Constant"), covariate.labels = c("demand elasticity", "first stage w"))
```